remote_theme: riggraz/no-style-please
title: Di Wu
author: Di Wu
email: hi@wudi.io
description: > 
  A programming engineer come from China.

permalink: /:slug.html

favicon: "logo.png"

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

goat_counter: wudi

sass:
  style: :compressed

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
